docs: add initial how-to doc
projector-cli/projector pull request #25
Opened 2021-01-13 23:50 UTC by elizabethhalper

## What did you implement:

Closes #24 

This is the initial commit for the how-to documentation. Written with end users in mind to guide them through commands and variables they will need to accomplish specific tasks using `pjr`. Also written with the intention of fleshing out as features get added. Please correct any incorrect assumptions I've made!

## How did you implement it:

Wrote it down :)

## Todos:

_**Note: Run `npm run check` to run all validation checks on proposed changes**_

- [X] Ensure there are no lint errors
       **Validate via `npm run lint`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [X] Write tests and confirm existing functionality is not broken
       **Validate via `npm test`**
- [X] Write documentation
- [X] Pull request title and commit message follows [the conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary)
- [X] Provide verification config / commands / resources
- [ ] Requested reviews from at least 2 individuals
- [X] Assigned PR to myself
- [X] Added PR to correct project
- [X] This is ready for review

**_Is it a breaking change?:_** NO

2021-01-14 17:30 UTC, tbarlow12 approved these changes
This is great. We can continue to iterate this on a team as well. I'd like to include a link to the How To doc in the README somewhere and I had a few other things to address before merging

2021-01-14 17:30 UTC, tbarlow12 commented on docs/how_to.md
> +  - Go to 'https://dev.azure.com/{organization}/_usersSettings/tokens' to generate a token
I think we can probably organize this section a little more. Maybe we can show what an example `agile` config would look like for Azure DevOps and explain the various parts. Something like...

#### What you need
- **baseUrl** - The base URL for your Azure DevOps organization. This usually has the format `https://dev.azure.com/{organizationName}`. If you are unsure how to create an organization, follow [these guidelines](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops).
- **accessToken** - A personal access token for your AzureDevOps organization. Go to `https://dev.azure.com/{organization}/_usersSettings/tokens` to generate a token.
- **projectName** - Name of your Azure DevOps project. `projector` does not currently support project creation, but will soon. Currently must be an existing project.

#### Example Config

```
...
"agile": {
    "providerName": "azdo",
    "providerOptions": {
        "baseUrl": "{baseUrl}",
        "projectName": "{projectName}",
        "personalAccessToken": "{accessToken}"
    }
    ...
}
```

2021-01-14 18:06 UTC, zmmille2 requested changes

2021-01-14 18:06 UTC, zmmille2 commented on docs/commands.md
> +    - [`pjr project init`](#pjr-project-init) - Initialize local projector configuration in `projector.json` file
This is an auto-generated file. If you wanna update stuff here (which I think is great) update the source 😁

2021-01-14 18:06 UTC, zmmille2 commented on package.json
> +    "axios": "^0.21.1",
please pin!

2021-01-14 18:06 UTC, zmmille2 commented on README.md
> +- [Table of Contents](#table-of-contents)
Might be good to link to the `how_to.md` from the README.md somewhere.

2021-01-14 18:06 UTC, zmmille2 commented on README.md
> +Projector is a tool that reduces repetitive work by creating CSE projects and backlogs using CLI commands. By running just a few commands, the tool sets up a project and backlog structure that reinfo
nit: I prefer sentences on newlines in Markdown.

2021-01-14 18:06 UTC, zmmille2 commented on docs/how_to.md
> +In order to initialize your local machine to use projector, you will run [`pjr project init`](./commands.md#pjr-project-init), but first you need the values shown below depending on the provider you
This paragraph needs a little love.
1. The sentence ends with "when ." When what?
2. We should provide the commands in the order people need them. "but first" is a bit of a red flag here - maybe we should rephrase?

2021-01-14 18:07 UTC, zmmille2 commented on package.json
> +    "axios": "^0.21.1",
Tanner covered this - resolving

2021-01-14 18:08 UTC, elizabethhalper commented on docs/how_to.md
> +Currently not supported, but is [in the backlog](https://github.com/projector-cli/projector/issues/14).
Fixed!

2021-01-14 18:09 UTC, elizabethhalper commented on docs/how_to.md
> +In order to initialize your local machine to use projector, you will run [`pjr project init`](./commands.md#pjr-project-init), but first you need the values shown below depending on the provider you
Good call! Revising now

2021-01-14 18:17 UTC, elizabethhalper commented on docs/how_to.md
> +  - Go to 'https://dev.azure.com/{organization}/_usersSettings/tokens' to generate a token
Great suggestions! Fixed!

2021-01-14 18:19 UTC, elizabethhalper commented on docs/commands.md
> +    - [`pjr project init`](#pjr-project-init) - Initialize local projector configuration in `projector.json` file
I believe I did only update it there, but I also ran `npm run docs:generate` and it showed up in diffs

2021-01-14 18:20 UTC, elizabethhalper commented on README.md
> +Projector is a tool that reduces repetitive work by creating CSE projects and backlogs using CLI commands. By running just a few commands, the tool sets up a project and backlog structure that reinfo
Yep its definitely a duplicate. I had written it before you wrote yours so good thing they look pretty much the same ;) I'll delete this and we can keep the `About` section!

2021-01-14 18:24 UTC, elizabethhalper commented on README.md
> +- [Table of Contents](#table-of-contents)
Added it to the "Getting Started" section

2021-01-14 22:53 UTC, alancast commented on README.md
> +## Table of Contents
I think it needs to be on the same line as the header, it still seems to be showing up in the TOC

2021-01-14 22:56 UTC, alancast commented on package.json
> +    "axios": "0.21.1",
I think this change has already been merged into master :-) So I think this and the package-lock.json can probably get reverted

2021-01-14 22:57 UTC, alancast commented on docs/how_to.md
> +            "personalAccessToken": "azd0spa6tl08ksl1kea6unch0fn3mbe8san6l3tt3rs"
lolol this is incredible

2021-01-14 22:58 UTC, alancast commented on docs/how_to.md
> +Currently not supported, but is [in the backlog](https://github.com/projector-cli/projector/issues/20).
nit: I feel like creating a repo in Azure Devops and in GitHub should likely be separate issues. They feel like they could have a lot of different things.

I know it's not part of this PR, but perhaps splitting those out into two separate issues if you agree

2021-01-14 22:59 UTC, alancast commented on docs/how_to.md
> +Currently not supported, but is [in the backlog](https://github.com/projector-cli/projector/issues/20).
But perhaps I'm wrong and they are basically the same. Some company named Microsoft does own both of them

2021-01-14 23:01 UTC, alancast approved these changes
Left a couple of suggestions but a super helpful doc and good to have around!

2021-01-14 23:13 UTC, elizabethhalper commented on README.md
> +## Table of Contents
Fixed!

2021-01-14 23:17 UTC, elizabethhalper commented on docs/how_to.md
> +Currently not supported, but is [in the backlog](https://github.com/projector-cli/projector/issues/20).
Hahah I totally agree, it'll be two separate issues. The issue itself acknowledges that and also says that it'll probably be split into multiple issues once implementation starts. It also mentions adding templated README's and working agreements so there are a lot of stories that need to come from it and I think I'd rather update it when we have more of it fleshed out.

2021-01-14 23:17 UTC, elizabethhalper commented on package.json
> +    "axios": "0.21.1",
Good catch! I'll just rebase and hopefully that will fix it

2021-01-19 16:05 UTC, zmmille2 approved these changes

2021-01-19 16:47 UTC, merged