feat: add ability to create project
projector-cli/projector pull request #50
Opened 2021-01-21 17:23 UTC by elizabethhalper

## What did you implement:

Closes #14 

Added ability to create and delete a project using the cli. User can do this by running
```
pjr agile project create -n <project-name> -d <project-description>
```
and
```
pjr agile project delete -n <project-name>
```

## How did you implement it:

- Added both sub-commands to the agile command
- Added functionality in the agileService provider (specifically the AzDo one)
- Added unit and integration tests

## Todos:

_**Note: Run `npm run check` to run all validation checks on proposed changes**_

- [X] Ensure there are no lint errors
       **Validate via `npm run lint`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [X] Write tests and confirm existing functionality is not broken
       **Validate via `npm test`**
- [X] Write documentation
- [X] Pull request title and commit message follows [the conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary)
- [X] Provide verification config / commands / resources
- [X] Requested reviews from at least 2 individuals
- [X] Assigned PR to myself
- [X] Added PR to correct project
- [X] This is ready for review

**_Is it a breaking change?:_** NO

2021-01-25 07:08 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Does this lint disable-next-line need to be here? It doesn't look like any is being used in the next line

2021-01-25 07:10 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
Can we add a comment explaining this magic GUID (I know you explained it to me but new folks won't understand)?

2021-01-25 07:13 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +      description: projectDescription || "",
Can we remove the `|| ""` if description is required?

2021-01-25 07:14 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Same question here about the ability to delete this lint disabler as it doesn't appear any is being used (but could be invalid in both cases)

2021-01-25 07:15 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
Perhaps we can put this GUID in a config somewhere if it is being used in a few files

2021-01-25 07:18 UTC, alancast commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +  .addAction(async (serviceCollection: ServiceCollection, options: ProjectInitializationOptions) => {
Can we remove options from this? If we are only getting the name from the ProjectInitializationOptions, and the command line takes in the name anyways, it feels redundant

2021-01-25 07:21 UTC, alancast commented on src/models/agile/agileService.ts
> +  deleteProject: (project: Project) => Promise<void>;
Can we look into having this return a `Promise<bool>`. Or if the underlying API makes that not trivial right now could we log an issue to attempt it in the future?

2021-01-25 07:25 UTC, alancast commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    // Poll until project exists
This isn't your fault but this is brutal. Wish their API allowed you to just await the creation. (But then it'd get less traffic and usage on the GET endpoint 😆)

2021-01-25 07:27 UTC, alancast commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    while (numLoops < 500) {
perhaps this should be a configurable amount of time. Feels like potentially an issue to log for later as it feels low priority. But worth a thought

2021-01-25 07:28 UTC, alancast commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +  deleteProject = async(project: Project): Promise<void> => {
Thoughts on having this just take in the projectId?

2021-01-25 07:30 UTC, alancast approved these changes

2021-01-25 15:45 UTC, tbarlow12 requested changes
Great start, and obviously it works. Left a few comments on some things I think should be resolved/addressed before merging. Thanks for this!

2021-01-25 15:45 UTC, tbarlow12 commented on docs/commands.md
> +  projector   Local Projector configuration
This I'm not quite sure about... I agree with you that the naming needs to be different to avoid confusion, but I don't love `projector` as a name. What about `conifg`?

2021-01-25 15:45 UTC, tbarlow12 commented on package.json
> +    "fs": "0.0.1-security",
Where is this being used?

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
Can we pipe this through config? We should probably stick it in `default.json` and use `Config` and a `ConfigValue` to get it. We can sync up later on how to do this.

Also, we should check to see if this is the template ID for the Agile-flavored project. Especially since we're in the `agile` subcommand, I think we can make the assumption (for now) that we'll be using an agile project

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +      visibility: coreInterfaces.ProjectVisibility.Private,
What other visibility options are there?

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +    await agileService.deleteProject(project);
Mentioned this in the demo, but a confirmation would be good here. Look at `UserUtils` for more info

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +  .description("Create Project with Agile Provider")
`Delete Project with Agile Provider`

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
Are these two lines being used?

2021-01-25 15:45 UTC, tbarlow12 commented on src/commands/commands/projector/projector.ts
> +export const projector = new Command()
See above comment regarding name. I think `config` should be used as the command name rather than `projector`

2021-01-25 15:45 UTC, tbarlow12 commented on src/models/agile/project.ts
>  export interface Project {
If we're wrapping the AzDO API, maybe let's call this interface `AzureDevOpsProject` or similar

2021-01-25 15:45 UTC, tbarlow12 commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.integration.test.ts
> +  it("can create and get a project", async () => {
nit: `can create, get and delete a project`

2021-01-25 15:45 UTC, tbarlow12 commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    // Poll until project exists
Agreed. I wonder why they don't allow the await, but this looks fine to me

2021-01-25 15:45 UTC, tbarlow12 commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    while (numLoops < 500) {
Should be fairly easy to make this configurable. I can help here if needed

2021-01-25 16:22 UTC, elizabethhalper commented on docs/commands.md
> +  projector   Local Projector configuration
sure that works for me!

2021-01-25 16:23 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
nope, removed!

2021-01-25 16:24 UTC, elizabethhalper commented on package.json
> +    "fs": "0.0.1-security",
I had added this when we were having issues with the `fs` package, but since we've changed those I'll remove this now

2021-01-25 16:24 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +  .description("Create Project with Agile Provider")
Good catch!

2021-01-25 16:30 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
These aren't being used--I created this really quickly for manually testing the delete capabilities by copying CreateProject and missed a few things. Deleting them now!

2021-01-25 16:36 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +  .addAction(async (serviceCollection: ServiceCollection, options: ProjectInitializationOptions) => {
I changed it so that it's now `ProjectDeleteOptions`. You're right in that it only has one property of the name so I could have just had an input of a string for the `projectName` but with the exported interface its extensible in case we want to add more options later.

2021-01-25 16:37 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/delete/agileProjectDelete.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
It's actually deleted from this file and only used in initialization but I agree that its messy. I'll put it in config somewhere.

2021-01-25 16:43 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +      visibility: coreInterfaces.ProjectVisibility.Private,
```
export enum ProjectVisibility {
    Unchanged = -1,
    /**
     * The project is only visible to users with explicit access.
     */
    Private = 0,
    /**
     * Enterprise level project visibility
     */
    Organization = 1,
    /**
     * The project is visible to all.
     */
    Public = 2,
    SystemPrivate = 3,
}
```
I can add that as an option and just put private or organization as default

2021-01-25 16:48 UTC, elizabethhalper commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    // Poll until project exists
Its so annoying. I may log an issue in the api

2021-01-25 19:26 UTC, elizabethhalper commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +  deleteProject = async(project: Project): Promise<void> => {
So we need the project Id for delete and the project name to get/poll (hate that from the API). But taking in the whole project is kinda clunky. Would you recommend taking in `projectId` and `projectName` instead of the whole project?

2021-01-25 19:26 UTC, elizabethhalper commented on src/models/agile/agileService.ts
> +  deleteProject: (project: Project) => Promise<void>;
Yup, had to do another ugly polling thing but was able to make it a boolean. Thanks for pointing that out bc I like that better too. I'll make a task to investigate alternatives to the polling mechanism though which might make the solution more elegant.

2021-01-25 20:19 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
Added it to config and added a comment above here to explain :)

2021-01-25 20:19 UTC, elizabethhalper commented on src/commands/commands/agile/commands/project/commands/create/agileProjectCreate.ts
> +    const templateId = "6b724908-ef14-45cf-84f8-768b5384da45";
added!

2021-01-25 20:22 UTC, elizabethhalper commented on src/services/agile/providers/azureDevOps/azureDevOpsAgileService.ts
> +    while (numLoops < 500) {
added to config!

2021-01-26 05:34 UTC, alancast commented on src/commands/commands/playbook/commands/template/commands/copy/playbookTemplateCopy.test.ts
> +import { CliSimulator, ModelSimulator, SimulatorAgileService, ServiceSimulator } from "../../../../../../../test";
Last comment is just making sure these changes are intentional

2021-01-27 00:03 UTC, elizabethhalper commented on src/commands/commands/playbook/commands/template/commands/copy/playbookTemplateCopy.test.ts
> +import { CliSimulator, ModelSimulator, SimulatorAgileService, ServiceSimulator } from "../../../../../../../test";
Good catch--this change left over from merging in master so I'll change it back to how it was originally

2021-01-27 15:57 UTC, tbarlow12 commented on src/config/default.json
> +      "templateTypeId": "6b724908-ef14-45cf-84f8-768b5384da45",
Does this template ID create `Agile` projects? Glad it's configurable - I think this is the same ID you had before and I just wanted to see if there's any way we could get the template ID used to create Agile flavored projects

2021-01-27 16:00 UTC, tbarlow12 commented on src/models/agile/project.ts
>  export interface Project {
I think that totally makes sense, I just think if this `Project` imports anything from the AzDO API, it's specific to AzDO. Maybe we create a `Project` interface and then an `AzureDevOpsProject` interface that inherits from `Project`?

I think this is fine for now and don't want to get too hung up on details, but maybe we can look at this in a future PR

2021-01-27 16:07 UTC, tbarlow12 approved these changes
LGTM - added a couple comments that may/may not be good to address before merging. I won't block on either one, but I do think they both need to be resolved eventually

2021-01-27 16:22 UTC, merged